#! /bin/bash

mail="<enter_email_address>"
password="<enter_password>"

base_url="https://now-dns.com/update?hostname="
hostname="<enter_hostname>"

/usr/bin/curl -u ${mail}:${password} "${base_url}${hostname}"
echo

